apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: apache-app  # Finds pods with the label 'app: apache-app'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
